num1 = input(" nhập số thứ nhất : ")
num2 = input(" nhập số thứ hai : ")
tong = float(num1) + float(num2)
num1 = float(num1)
num2 = float(num2)
print(f"tong cua 2 so hang la : {tong} ")
hieu = float(num1) - float(num2)
print(f"hieu cua 2 so hang la : {hieu} ")
tich = float(num1) * float(num2)
print(f"tich cua 2 so hang la : {tich} ")
thuong = float(num1) / float(num2)
print(f"thuong cua 2 so hanng la : {thuong}")